version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: parser_tg_bot
    restart: always
    env_file:
      - .env
    working_dir: /app
    command: python main.py
    volumes:
      - /root/ParserTgChats/Property.session:/app/Property.session
      - /root/ParserTgChats/bot.db:/app/bot.db
